spring:

  config:
    import: properties/auth.yml

  sql:
    init:
      mode: always
      #data-locations: classpath:bulk-data.sql

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/testdb?allowLoadLocalInfile=true
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: none

    #defer-datasource-initialization: true

    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true

    open-in-view: false

  redis:
    port: 6379
    host: localhost

  cache:
    type: redis
    redis:
      time-to-live: 5000000
